# Shakespeare Player Classification #

In this project we'll try to determine which Shakespearean character is speaking during any given line using only information about the play and the line itself.  To accomplish this, we'll engineer a few features on the given dataset and also

Sources:
- Shakespeare Line Data: https://www.kaggle.com/kingburrito666/shakespeare-plays/data

## Read and clean data
First we'll read in our dataset and throw out values that are either misformatted or not relevant to our project.

In [1]:
#But imports first!
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer
from numpy import concatenate, hstack, unique
import scipy.sparse as sparse
from sklearn.metrics import f1_score, classification_report, confusion_matrix


raw_data = pd.read_csv('./data/shakespeare_data.csv')
raw_data.head()

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine
0,1,Henry IV,NaN,NaN,NaN,ACT I
1,2,Henry IV,NaN,NaN,NaN,SCENE I. London. The palace.
2,3,Henry IV,NaN,NaN,NaN,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ..."
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,"
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,"

## Dataset info
**Column definitions** 

| Column   | Description |
| :---------| :---------------
| `Dataline` | unique ID for a line |
|`Play` | Play the line is from |
|`PlayerLinenumber` | The line being spoken |
|`ActSceneLine` | Act.Scene.Line the play is from |
|`Player` | The player reading the line|
|`PlayerLine`| The line being spoken|

## Cleaning Data
#### Narrator
There seems to be narrator and stage direction lines through out our data set with Player as `Nan`.  While we could reassign these to a value such as `NARRATOR`, instead we'll remove them from our data set since the narrator is quite different from all of the other characters across the dataset.

#### Dataline Column
The dataline column isn't contributing anything to our dataset, it's just a sequential ID.  We'll take it out to make our dataset just the info that matters.

#### Stage Directions & Scene Info
Many lines contain information about the setting, stage directions, and scene info.  These typically have null values for one of the `PlayerLinenumber`, `ActSceneLine`, or `Player` columns.  We'll remove these lines as well.

In [2]:
#Take these values out!
raw_data.query("ActSceneLine.isnull() or Player.isnull() or PlayerLinenumber.isnull()", engine = 'python')

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine
0,1,Henry IV,NaN,NaN,NaN,ACT I
1,2,Henry IV,NaN,NaN,NaN,SCENE I. London. The palace.
2,3,Henry IV,NaN,NaN,NaN,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ..."
111,112,Henry IV,10.0,NaN,WESTMORELAND,Exeunt
112,113,Henry IV,10.0,NaN,WESTMORELAND,SCENE II. London. An apartment of the Prince's.
...,...,...,...,...,...,...
111208,111209,A Winters Tale,38.0,NaN,Clown,"Enter LEONTES, POLIXENES, FLORIZEL, PERDITA, C..."
111232,111233,A Winters Tale,4.0,NaN,PAULINA,"PAULINA draws a curtain, and discovers HERMION..."
111330,111331,A Winters Tale,30.0,NaN,PAULINA,Music
111336,111337,A Winters Tale,30.0,NaN,PAULINA,HERMIONE comes down
111395,111396,A Winters Tale,38.0,NaN,LEONTES,Exeunt

In [3]:
#Cleaned dataset!
lines = raw_data.query("ActSceneLine.notnull() and Player.notnull() and PlayerLinenumber.notnull()", engine = 'python').copy()
del lines['Dataline']

### Creating usable data
Let's give each Act, Scene, and Line it's own column here and change types to floats.  We'll also encode each play using one-hot encoding.

In [4]:
lines.head()

,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine
3,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,"
4,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,"
5,Henry IV,1.0,1.1.3,KING HENRY IV,And breathe short-winded accents of new broils
6,Henry IV,1.0,1.1.4,KING HENRY IV,To be commenced in strands afar remote.
7,Henry IV,1.0,1.1.5,KING HENRY IV,No more the thirsty entrance of this soil

In [5]:
#Create new columns for act, scene, and line
lines['Act'] = lines.apply(lambda row : int(str(row.ActSceneLine).split('.')[0]), axis=1)
lines['Scene'] = lines.apply(lambda row : int(str(row.ActSceneLine).split('.')[1]), axis=1)
lines['Line'] = lines.apply(lambda row : int(str(row.ActSceneLine).split('.')[2]), axis=1)
lines.drop(columns=["ActSceneLine"], inplace=True)
lines['LineLength'] = lines.apply(lambda row : len(row.PlayerLine), axis=1)

# One hot encode the Play name
lines = pd.get_dummies(lines, columns = ["Play"])

# Standardize PlayerLine (remove punctuation & all lowercase)
lines ['PlayerLine'] = lines['PlayerLine'].apply(lambda x: re.sub('[^a-zA-z0-9\s]', '', x).lower())

# Show us that progress!
lines.head()

,PlayerLinenumber,Player,PlayerLine,Act,Scene,Line,LineLength,Play_A Comedy of Errors,Play_A Midsummer nights dream,Play_A Winters Tale,...,Play_Richard III,Play_Romeo and Juliet,Play_Taming of the Shrew,Play_The Tempest,Play_Timon of Athens,Play_Titus Andronicus,Play_Troilus and Cressida,Play_Twelfth Night,Play_Two Gentlemen of Verona,Play_macbeth
3,1.0,KING HENRY IV,so shaken as we are so wan with care,1,1,1,38,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.0,KING HENRY IV,find we a time for frighted peace to pant,1,1,2,42,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1.0,KING HENRY IV,and breathe shortwinded accents of new broils,1,1,3,46,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1.0,KING HENRY IV,to be commenced in strands afar remote,1,1,4,39,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1.0,KING HENRY IV,no more the thirsty entrance of this soil,1,1,5,41,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Bag of Words 

In order to give a numerical representation to our `PlayerLine` column, we'll be using the Bag of Words approach described here: https://scikit-learn.org/stable/modules/feature_extraction.html#the-bag-of-words-representation

In [6]:
# Init the Vectorizer
vectorizer = CountVectorizer()

# Vectorize the PlayerLines
vectorized_lines = vectorizer.fit_transform(lines['PlayerLine'])
vectorized_lines

<105152x27199 sparse matrix of type '<class 'numpy.int64'>'
	with 729870 stored elements in Compressed Sparse Row format>

In [7]:
features = lines.copy()
features.drop(columns=["Player", "PlayerLine"], inplace=True)
complete_features = sparse.hstack( [sparse.csr_matrix(features), vectorized_lines])

## Classification
To show the added value of features we add on, let's try and classify the players with a few different methods with only the data we have been provided.

We'll try using a SVM and KNN model to see what kind of results we get. We'll choose K to be the number of players in our dataset:

In [8]:
# Find the K for K nearest neighbors
players = lines['Player'].unique()
K = len(players)
K

934

In [9]:
from sklearn.model_selection import train_test_split

#Define our labels & features, then split into training and test data
labels = lines.loc[: , ["Player"]] #Player is our label of interest
feature_train, feature_test, label_train, label_test = train_test_split(complete_features, labels, test_size=0.20, random_state=27)

### Initialize, Train, and Test the Models
Now we'll train and test our models.  We'll be using a SVM, K-Nearest Neighbors, and Decision Tree models.  Our test data was 20% of our total data set.

To get a better understanding of our results, we'll also look at the confusion matrix for our SVC model and the classification report for our KNN model (K = 934) as well.

In [10]:
from sklearn.svm import SVC
#Initialize the model
SVM_model = SVC()

#Training
SVM_model.fit(feature_train, label_train)

#Predict
SVM_prediction = SVM_model.predict(feature_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [11]:
from sklearn.tree import DecisionTreeClassifier
#Initialize the model
DT_model = DecisionTreeClassifier()

#Training
DT_model.fit(feature_train, label_train)

#Predict
DT_prediction = DT_model.predict(feature_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
#Initialize the model
KNN_model = KNeighborsClassifier(n_neighbors=K)

#Training
KNN_model.fit(feature_train, label_train)

#Predict
KNN_prediction = KNN_model.predict(feature_test)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

In [13]:
#View our results for SVM
print(f1_score(SVM_prediction, label_test, average = 'weighted', labels = unique(SVM_prediction)))
print(confusion_matrix(SVM_prediction, label_test))

0.05791334695723195
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [16]:
#View our results for Decision Tree Classification
print(f1_score(DT_prediction, label_test, average = 'weighted', labels = unique(DT_prediction)))

0.6969477652121824

In [15]:
#View our Results for KNN
print(f1_score(KNN_prediction, label_test, average = 'weighted', labels = unique(KNN_prediction)))
print(classification_report(KNN_prediction, label_test))

0.07170349235415517

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)

                    precision    recall  f1-score   support

            A Lord       0.00      0.00      0.00         0
          A Player       0.00      0.00      0.00         0
             AARON       0.03      0.04      0.04        50
       ABERGAVENNY       0.00      0.00      0.00         0
          ABHORSON       0.00      0.00      0.00         0
           ABRAHAM       0.00      0.00      0.00         0
          ACHILLES       0.00      0.00      0.00         0
              ADAM       0.00      0.00      0.00         0
            ADRIAN       0.00      0.00      0.00         0
           ADRIANA       0.16      0.05      0.08       154
 ADRIANO DE ARMADO       0.00      0.00      0.00         0
            AEGEON       0.00      0.00      0.00         0
           AEMELIA       0.00      0.00      0.00         0
          AEMILIUS       0.00      0.00      0.00         0
            AENEAS       0.00      0.00      0.00         1
            AEdile       0.00      0.00      0.00         0
         AGAMEMNON       0.00      0.00      0.00         0
           AGRIPPA       0.00      0.00      0.00         0
              AJAX       0.00      0.00      0.00         0
            ALBANY       0.00      0.00      0.00         0
        ALCIBIADES       0.00      0.00      0.00         0
           ALENCON       0.00      0.00      0.00         0
         ALEXANDER       0.00      0.00      0.00         0
            ALEXAS       0.00      0.00      0.00         0
             ALICE       0.00      0.00      0.00         0
               ALL       0.00      0.00      0.00         0
            ALONSO       0.00      0.00      0.00         0
            AMIENS       0.00      0.00      0.00         0
        ANDROMACHE       0.00      0.00      0.00         0
            ANGELO       0.00      0.00      0.00         3
             ANGUS       0.00      0.00      0.00         0
              ANNE       0.00      0.00      0.00         0
         ANNE PAGE       0.00      0.00      0.00         0
         ANTIGONUS       0.00      0.00      0.00         0
         ANTIOCHUS       0.00      0.00      0.00         0
        ANTIPHOLUS       0.00      0.00      0.00         0
           ANTONIO       0.08      0.06      0.07       130
            ANTONY       0.00      0.00      0.00         2
         APEMANTUS       0.00      0.00      0.00         0
ARCHBISHOP OF YORK       0.00      0.00      0.00         0
        ARCHIDAMUS       0.00      0.00      0.00         0
             ARIEL       0.00      0.00      0.00         0
            ARMADO       0.00      0.00      0.00         0
           ARRAGON       0.00      0.00      0.00         0
       ARTEMIDORUS       0.00      0.00      0.00         0
            ARTHUR       0.00      0.00      0.00         0
         ARVIRAGUS       0.00      0.00      0.00         0
            AUDREY       0.00      0.00      0.00         0
          AUFIDIUS       0.02      0.10      0.03        10
           AUSTRIA       0.00      0.00      0.00         0
         AUTOLYCUS       0.28      0.20      0.23        84
             Abbot       0.00      0.00      0.00         0
               All       0.00      0.00      0.00         0
         All Lords       0.00      0.00      0.00         0
      All Servants       0.00      0.00      0.00         0
             BAGOT       0.00      0.00      0.00         0
         BALTHASAR       0.00      0.00      0.00         0
         BALTHAZAR       0.00      0.00      0.00         0
            BANQUO       0.00      0.00      0.00         0
          BAPTISTA       0.00      0.00      0.00         0
          BARDOLPH       0.00      0.00      0.00         0
          BASSANIO       0.00      0.00      0.00         0
            BASSET       0.00      0.00      0.00         0
         BASSIANUS       0.00      0.00      0.00         0
           BASTARD       0.00      0.00      0.00         0
BASTARD OF ORLEANS       0.00      0.00      0.00         0
             BATES       0.00      0.00      0.00         0
          BEATRICE       0.00      0.00      0.00         0
           BEDFORD       0.00      0.00      0.00         0
          BELARIUS       0.00      0.00      0.00         0
          BENEDICK       0.17      0.09      0.12       173
          BENVOLIO       0.00      0.00      0.00         0
          BERNARDO       0.00      0.00      0.00         0
           BERTRAM       0.00      0.00      0.00         0
             BEVIS       0.00      0.00      0.00         0
            BIANCA       0.00      0.00      0.00         0
             BIGOT       0.00      0.00      0.00         0
         BIONDELLO       0.00      0.00      0.00         0
             BIRON       0.01      0.33      0.03         6
BISHOP OF CARLISLE       0.00      0.00      0.00         0
     BISHOP OF ELY       0.00      0.00      0.00         0
            BLANCH       0.00      0.00      0.00         0
             BLUNT       0.00      0.00      0.00         0
       BOLINGBROKE       0.00      0.00      0.00         0
              BONA       0.00      0.00      0.00         0
          BORACHIO       0.00      0.00      0.00         0
              BOTH       0.00      0.00      0.00         0
            BOTTOM       0.00      0.00      0.00         0
             BOULT       0.00      0.00      0.00         0
           BOURBON       0.00      0.00      0.00         0
             BOYET       0.00      0.00      0.00         0
         BRABANTIO       0.00      0.00      0.00         0
        BRAKENBURY       0.00      0.00      0.00         0
           BRANDON       0.00      0.00      0.00         0
            BRUTUS       0.10      0.03      0.05       537
        BUCKINGHAM       0.04      0.07      0.05        86
          BURGUNDY       0.00      0.00      0.00         0
             BUSHY       0.00      0.00      0.00         0
          Banditti       0.00      0.00      0.00         0
              Bawd       0.00      0.00      0.00         0
         Boatswain       0.00      0.00      0.00         0
              Both       0.00      0.00      0.00         0
     Both Tribunes       0.00      0.00      0.00         0
               Boy       0.00      0.00      0.00         1
              CADE       0.02      0.50      0.03         2
            CAESAR       0.00      0.00      0.00         0
         CAITHNESS       0.00      0.00      0.00         0
      CAIUS LUCIUS       0.00      0.00      0.00         0
           CALCHAS       0.00      0.00      0.00         0
           CALIBAN       0.00      0.00      0.00         0
         CALPURNIA       0.00      0.00      0.00         0
         CAMBRIDGE       0.00      0.00      0.00         0
           CAMILLO       0.29      0.14      0.19       124
          CANIDIUS       0.00      0.00      0.00         0
        CANTERBURY       0.00      0.00      0.00         0
            CAPHIS       0.00      0.00      0.00         0
          CAPUCIUS       0.00      0.00      0.00         0
           CAPULET       0.03      0.04      0.04        53
          CARDINAL       0.00      0.00      0.00         0
 CARDINAL CAMPEIUS       0.00      0.00      0.00         0
 CARDINAL PANDULPH       0.00      0.00      0.00         0
   CARDINAL WOLSEY       0.00      0.00      0.00         0
             CASCA       0.00      0.00      0.00         0
         CASSANDRA       0.00      0.00      0.00         0
            CASSIO       0.00      0.00      0.00         0
           CASSIUS       0.11      0.05      0.07       252
           CATESBY       0.00      0.00      0.00         0
              CATO       0.00      0.00      0.00         0
             CELIA       0.00      0.00      0.00        46
             CERES       0.00      0.00      0.00         0
           CERIMON       0.00      0.00      0.00         0
           CHARLES       0.00      0.00      0.00         2
          CHARMIAN       0.00      0.00      0.00         0
         CHATILLON       0.00      0.00      0.00         0
            CHIRON       0.00      0.00      0.00         0
            CICERO       0.00      0.00      0.00         0
             CINNA       0.00      0.00      0.00         0
    CINNA THE POET       0.00      0.00      0.00         0
          CLARENCE       0.00      0.00      0.00         0
           CLAUDIO       0.01      0.01      0.01        70
          CLAUDIUS       0.00      0.00      0.00         0
         CLEOMENES       0.00      0.00      0.00         0
             CLEON       0.00      0.00      0.00         0
         CLEOPATRA       0.06      0.04      0.05       241
          CLIFFORD       0.00      0.00      0.00         1
            CLITUS       0.00      0.00      0.00         0
            CLOTEN       0.00      0.00      0.00         1
            COBWEB       0.00      0.00      0.00         0
          COMINIUS       0.00      0.00      0.00         0
           CONRADE       0.00      0.00      0.00         0
         CONSTANCE       0.00      0.00      0.00         0
          CORDELIA       0.00      0.00      0.00         0
             CORIN       0.00      0.00      0.00         0
        CORIOLANUS       0.07      0.04      0.05       215
         CORNELIUS       0.00      0.00      0.00         0
          CORNWALL       0.00      0.00      0.00         0
           COSTARD       0.00      0.00      0.00         0
          COUNTESS       0.00      0.00      0.00         1
             COURT       0.00      0.00      0.00         0
           CRANMER       0.00      0.00      0.00         0
          CRESSIDA       0.08      0.17      0.11        24
          CROMWELL       0.00      0.00      0.00         0
             CURAN       0.00      0.00      0.00         0
             CURIO       0.00      0.00      0.00         0
            CURTIS       0.00      0.00      0.00         0
         CYMBELINE       0.00      0.00      0.00         0
           Captain       0.00      0.00      0.00         0
       Chamberlain       0.00      0.00      0.00         0
        Chancellor       0.00      0.00      0.00         0
            Chorus       0.57      0.12      0.19       303
           Citizen       0.00      0.00      0.00         0
          Citizens       0.00      0.00      0.00         0
             Clerk       0.00      0.00      0.00         0
             Clown       0.25      0.04      0.08       876
         Constable       0.00      0.00      0.00         0
         Courtezan       0.00      0.00      0.00         0
             Crier       0.00      0.00      0.00         0
             Cupid       0.00      0.00      0.00         0
           DAUPHIN       0.00      0.00      0.00         0
     DECIUS BRUTUS       0.00      0.00      0.00         0
         DEMETRIUS       0.00      0.00      0.00         0
             DERBY       0.00      0.00      0.00         0
          DERCETAS       0.00      0.00      0.00         0
         DESDEMONA       0.01      0.02      0.02        50
             DIANA       0.00      0.00      0.00         0
              DICK       0.00      0.00      0.00         0
          DIOMEDES       0.00      0.00      0.00         0
              DION       0.00      0.00      0.00         0
           DIONYZA       0.05      1.00      0.09         1
      DOCTOR BUTTS       0.00      0.00      0.00         0
      DOCTOR CAIUS       0.00      0.00      0.00         0
          DOGBERRY       0.00      0.00      0.00         0
         DOLABELLA       0.00      0.00      0.00         0
DOMITIUS ENOBARBUS       0.00      0.00      0.00        35
          DON JOHN       0.00      0.00      0.00         0
         DON PEDRO       0.00      0.00      0.00         0
         DONALBAIN       0.00      0.00      0.00         0
            DORCAS       0.00      0.00      0.00         0
            DORSET       0.00      0.00      0.00         0
 DROMIO OF EPHESUS       0.00      0.00      0.00         0
DROMIO OF SYRACUSE       0.12      0.05      0.07       168
           DUCHESS       0.00      0.00      0.00         1
   DUCHESS OF YORK       0.00      0.00      0.00         3
              DUKE       0.00      0.00      0.00         5
    DUKE FREDERICK       0.00      0.00      0.00         0
   DUKE OF AUMERLE       0.00      0.00      0.00         0
    DUKE OF SURREY       0.00      0.00      0.00         0
    DUKE OF VENICE       0.00      0.00      0.00         0
      DUKE OF YORK       0.00      0.00      0.00         0
       DUKE ORSINO       0.00      0.00      0.00         0
       DUKE SENIOR       0.00      0.00      0.00         0
      DUKE SOLINUS       0.00      0.00      0.00         0
    DUKE VINCENTIO       0.06      0.05      0.05       196
              DULL       0.00      0.00      0.00         0
            DUMAIN       0.00      0.00      0.00        10
            DUNCAN       0.00      0.00      0.00         0
             Danes       0.00      0.00      0.00         0
            Doctor       0.00      0.00      0.00         0
   EARL OF DOUGLAS       0.00      0.00      0.00         0
 EARL OF SALISBURY       0.00      0.00      0.00         0
 EARL OF WORCESTER       0.00      0.00      0.00         0
             EDGAR       0.00      0.00      0.00         0
            EDMUND       0.00      0.00      0.00         0
            EDWARD       0.00      0.00      0.00         0
             EGEUS       0.00      0.00      0.00         0
          EGLAMOUR       0.00      0.00      0.00         0
             ELBOW       0.00      0.00      0.00         0
               ELY       0.00      0.00      0.00         0
            EMILIA       0.00      0.00      0.00         0
              EROS       0.00      0.00      0.00         0
           ESCALUS       0.00      0.00      0.00         0
             ESSEX       0.00      0.00      0.00         0
            EXETER       0.00      0.00      0.00         0
             EXTON       0.00      0.00      0.00         0
          Egyptian       0.00      0.00      0.00         0
    English Herald       0.00      0.00      0.00         0
            FABIAN       0.00      0.00      0.00         0
          FALSTAFF       0.19      0.03      0.06      1215
          FASTOLFE       0.00      0.00      0.00         0
            FENTON       0.00      0.00      0.00         0
         FERDINAND       0.00      0.00      0.00        36
         FLAMINIUS       0.00      0.00      0.00         0
           FLAVIUS       0.02      0.20      0.04         5
          FLORIZEL       0.00      0.00      0.00         0
          FLUELLEN       0.08      0.13      0.10        31
             FLUTE       0.00      0.00      0.00         0
              FORD       0.00      0.00      0.00         0
           FRANCIS       0.00      0.00      0.00         0
         FRANCISCO       0.00      0.00      0.00         0
       FRENCH KING       0.00      0.00      0.00         0
     FRIAR FRANCIS       0.00      0.00      0.00         0
        FRIAR JOHN       0.00      0.00      0.00         0
    FRIAR LAURENCE       0.00      0.00      0.00         0
       FRIAR PETER       0.00      0.00      0.00         0
      FRIAR THOMAS       0.00      0.00      0.00         0
             FROTH       0.00      0.00      0.00         0
             Fairy       0.00      0.00      0.00         0
            Father       0.00      0.00      0.00         0
  First Ambassador       0.00      0.00      0.00         0
  First Apparition       0.00      0.00      0.00         0
      First Bandit       0.00      0.00      0.00         0
     First Brother       0.00      0.00      0.00         0
     First Captain       0.00      0.00      0.00         0
     First Carrier       0.00      0.00      0.00         0
     First Citizen       0.00      0.00      0.00         0
       First Clown       0.00      0.00      0.00         0
 First Conspirator       0.00      0.00      0.00         0
 First Executioner       0.00      0.00      0.00         0
   First Fisherman       0.00      0.00      0.00         0
      First Gaoler       0.00      0.00      0.00         0
   First Gentleman       0.02      0.01      0.01       106
        First Goth       0.00      0.00      0.00         0
       First Guard       0.00      0.00      0.00         0
      First Herald       0.00      0.00      0.00         0
    First Huntsman       0.00      0.00      0.00         0
      First Keeper       0.00      0.00      0.00         0
        First Lady       0.00      0.00      0.00         0
        First Lord       0.00      0.00      0.00         0
    First Merchant       0.00      0.00      0.00         0
   First Messenger       0.00      0.00      0.00         0
    First Murderer       0.00      0.00      0.00         0
    First Musician       0.00      0.00      0.00         0
   First Neighbour       0.00      0.00      0.00         0
     First Officer       0.00      0.00      0.00         0
      First Outlaw       0.00      0.00      0.00         0
  First Petitioner       0.00      0.00      0.00         0
      First Player       0.00      0.00      0.00         0
      First Priest       0.00      0.00      0.00         0
      First Sailor       0.00      0.00      0.00         0
   First Secretary       0.00      0.00      0.00         0
     First Senator       0.00      0.00      0.00         0
     First Servant       0.00      0.00      0.00         0
  First Servingman       0.00      0.00      0.00         0
     First Soldier       0.00      0.00      0.00         0
    First Stranger       0.00      0.00      0.00         0
   First Traveller       0.00      0.00      0.00         0
    First Watchman       0.00      0.00      0.00         0
       First Witch       0.00      0.00      0.00        36
              Fool       0.00      0.00      0.00        18
          Forester       0.00      0.00      0.00         0
    Fourth Citizen       0.00      0.00      0.00         0
    Fourth Soldier       0.00      0.00      0.00         0
     French Herald       0.00      0.00      0.00         0
    French Soldier       0.00      0.00      0.00         0
         Frenchman       0.00      0.00      0.00         0
          GADSHILL       0.00      0.00      0.00         0
          GARDENER       0.00      0.00      0.00         0
          GARDINER       0.00      0.00      0.00         0
            GEORGE       0.00      0.00      0.00         0
             GHOST       0.00      0.00      0.00         0
         GLANSDALE       0.00      0.00      0.00         0
         GLENDOWER       0.00      0.00      0.00         0
        GLOUCESTER       0.36      0.03      0.06      4332
             GOBBO       0.00      0.00      0.00         0
           GONERIL       0.00      0.00      0.00         0
           GONZALO       0.00      0.00      0.00         0
          GOVERNOR       0.00      0.00      0.00         0
             GOWER       0.03      0.04      0.03        50
          GRANDPRE       0.00      0.00      0.00         0
          GRATIANO       0.00      0.00      0.00         0
             GREEN       0.00      0.00      0.00         0
           GREGORY       0.00      0.00      0.00         0
            GREMIO       0.00      0.00      0.00         0
              GREY       0.00      0.00      0.00         0
          GRIFFITH       0.00      0.00      0.00         0
            GRUMIO       0.00      0.00      0.00         0
         GUIDERIUS       0.00      0.00      0.00         0
      GUILDENSTERN       0.00      0.00      0.00         0
         GUILDFORD       0.00      0.00      0.00         0
            Gaoler       0.00      0.00      0.00         0
          Gardener       0.00      0.00      0.00         0
           General       0.00      0.00      0.00         0

## Summary
SVM struggled with a 6% precision rating.  

Decision Tree did well, correctly identifying ~70% of lines.

KNN did awfully with a 7% precision, having so many different 'neighbors' with so few data points likely contributes to this.

Going forward, other methods such as random forest may do well since Play name nicely partitions the labels!